[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions_nvs_app.csv

build_flags =
  -std=gnu++17
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
  -Wno-error=old-style-declaration
  -Wno-old-style-declaration
  -I components/ais_commonlib/include/architectureabs
  -I components/ais_commonlib/include/logger
  -I components/ais_commonlib/
  -I components/ais_framework/include/HAL
  -I components/ais_framework/
  -I components/ais_framework/include/OSAL/ESP32
  -I components/ais_framework/include/OSAL/Platform
  -I include
  -I src
